language: node_js
notifications:
  slack:
    rooms:
      secure: FQp2FS0i8m7f0NYsVGXznfBFAWTS8/jr7dau8t7oAUufIosGF7YX/CMWNRicdXuzpl1NX7AIEFVDA2bT5PkviKbfEI0sHoarfWazLVn5aaPft8WKfA/vcE8YNVghI1X7RbImZOqoEYQI6VktutidGYwy7dQgLEWImtleri/irmwejtYQqYASYA/lCSOsIoePdyiWfuLCVJw0Cpkop5ufDUp5Li9eCq8x/3peEL/pz+HFxqVwil19/kRAOzJirQ8TozzXJxgUoHzPv6JAUgn8jQ2kNjX4Zm8UKZfPr4/IFL+Xb2n3ZPKTobjGI4ZOFgQDaaOlCxEHjL9zJFFbwmlfJng32jZscLH4VmPI2OVINP7O1pXBXhRXpUZLbrAMHKmONjN3hc7xU/x7AqFmlQafz0ggM+iRkiiPzhio/DL4+sNEfFRAjaBH3gyLKqk9JC+GTfWkCYhUg39Sh4McgNkxUwOQAFsv6O4bK1EpzqNQc+F/TAGgrrO9fTOWaAgWn/9lZ6wTwNr/s+o+3tYlBWaryXLTyJirD8q2ECAPvJBGZhzNhumZjGIfiJuWQV9h4xG6gFnh3BEF2iKBSu4LE53bTQvVG6Y0ZuDmQPM+Ha+ZineaAF4nDKTZmGV3JdCwLZ3DLKkc4Q+k5QUdli9wsoBB+l+ot0YcbnCLZ2padJ3zJn0=
    on_success: change
    on_failure: always
    on_error: always
    on_cancel: always
services:
  - mongodb
  - rabbitmq
  - docker
env:
  - REPO=poetapp/node
before_script:
  - sudo make ipfs
  - npm run build
  - npm run test-prepare-db
  - sleep 5
  - npm start &
  - sleep 5
script:
  - npm run lint
  - npm run coverage
before_deploy:
  - bash ./scripts/docker-build.sh
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - bash ./scripts/docker-push.sh
    on:
      all_branches: true
after_deploy:
  - npm run travis-deploy-once "npm run semantic-release"