version: '3'

services:
  mongo:
    image: mongo:3.4
    ports:
    - "27017:27017"
    
  rabbit:
    image: rabbitmq:3
    ports:
    - "5671:5671"
    - "5672:5672"
    - "15672:15672"
    hostname: my-rabbit
    
  ipfs:
    image: ipfs/go-ipfs:v0.4.17
    ports:
    - "8080:8080"
    - "4001:4001"
    - "5001:5001"
    volumes:
    - .ipfs-docker:/data/ipfs
    
  bitcoin-regtest:
    image: ruimarinho/bitcoin-core:0.16.3
    ports:
    - "18443:18443"
    command:
      -printtoconsole
      -server
      -regtest=1
      -rpcuser=bitcoinrpcuser
      -rpcpassword=bitcoinrpcpassword
      -rpcallowip=::/0
