version: '3'

services:
  bitcoind-2:
    image: ruimarinho/bitcoin-core:0.17.0
    ports:
      - "19443:18443"
    command:
      -printtoconsole
      -testnet=${USE_BTC_TESTNET:-0}
      -regtest=${USE_BTC_REGTEST:-1}
      -rpcuser=bitcoinrpcuser
      -rpcpassword=bitcoinrpcpassword
      -rpcallowip=::/0
      -server
      -deprecatedrpc=signrawtransaction
      -addnode=bitcoind-1
    links:
      - bitcoind-1
