version: '3'

services:
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
      - ./mongodb:/docker-entrypoint-initdb.d

  rabbit:
    image: rabbitmq:3
    ports:
      - "5671:5671"
      - "5672:5672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=some_secret_cookie
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=adminPass

  ipfs:
    image: ipfs/go-ipfs:v0.4.17
    ports:
      - "8080:8080"
      - "4001:4001"
      - "5001:5001"
    volumes:
      - data:/data/ipfs

  bitcoind-1:
    image: ruimarinho/bitcoin-core:0.17.0
    ports:
      - "18443:18443"
    command:
      -printtoconsole
      -server
      -testnet=${USE_BTC_TESTNET:-0}
      -regtest=${USE_BTC_REGTEST:-1}
      -rpcuser=bitcoinrpcuser
      -rpcpassword=bitcoinrpcpassword
      -rpcallowip=::/0
      -deprecatedrpc=signrawtransaction

  poet-node:
    build: .
    ports:
      - "18080:18080"
    depends_on:
      - mongo
      - rabbit
      - ipfs
      - bitcoind-1
    environment:
      - POET_SERVICE=node
      - BITCOIN_URL=bitcoind-1
      - RABBITMQ_URL=amqp://admin:adminPass@rabbit
      - MONGODB_HOST=mongo
      - IPFS_URL=http://ipfs:5001
      - INTEGRATION_TEST_NODE_URL=http://poet-node:18080
    links:
      - mongo
      - rabbit
      - ipfs
      - bitcoind-1
    command: >
      /bin/bash -c "
        sleep 10;
        npm start;
        "

volumes:
  db:
    driver: local

  data:
    driver: local
