version: '3'
services:
  poet-node:
    build: .
    ports:
      - "18080:18080"
    depends_on:
      - mongo
      - rabbit
      - ipfs
      - bitcoin-regtest
    environment:
      - BITCOIN_URL=bitcoin-regtest
      - RABBITMQ_URL=amqp://poet-rabbit
      - MONGODB_URL=mongodb://poet-mongo:27017/poet
      - IPFS_URL=http://poet-ipfs:5001
      - INTEGRATION_TEST_MONGODB_URL=mongodb://poet-mongo:27017/poet
      - INTEGRATION_TEST_NODE_URL=http://poet-node:18080
    hostname: poet-node
    links:
      - mongo
      - rabbit
      - ipfs
      - bitcoin-regtest
    command: >
      /bin/bash -c "
        sleep 10;
        npm start;
      "
